#/appspec.yml
# docker-compose로 deploy 할 것임.
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
hooks:
  BeforeInstall:
    - location: /initialize.sh
      runas: ubuntu

  ApplicationStart:
    - location: /start.sh
      runas: ubuntu
      # ubuntu의 $HOME 환경변수를 이용해보려고 runas ubuntu