#/appspec.yml
# docker-compose로 deploy 할 것임.
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/meet-api
hooks:
  BeforeInstall:
    - location: /codepipeline-scripts/initialize.sh
      runas: root

  ApplicationStart:
    - location: /codepipeline-scripts/start.sh
      runas: root
      #ubuntu의 $HOME 환경변수를 이용해보려고 runas ubuntu