version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo start installing ...
      # - npm install # 어차피 docker-compose에서 build할 때 알아서 npm install함.
  post_build:
    commands:
      - echo start downloading credentials from S3 bucket
      - aws s3 cp --recursive s3://umi0410-credentials/meet-api/ .
      - cat test>test

artifacts:
  files:
    - "**/*"
cache:
  paths:
    - "node_modules/**/*"