# meet-api 를 위한 express와 mongo container의 docker-compose
version: '3.7'

services:
  mongo-container:
    image: mongo
    # 이거 까먹어선 안됨!!
    volumes:
      - $HOME/mongoData:/data/db

  express-container:
    depends_on:
      - mongo-container
    # ECR에서 meet-api repository의 latest 이미지를 가져온다.
    # image: 325498511266.dkr.ecr.ap-northeast-2.amazonaws.com/meet-api:latest

    # 근데 이게 더 편할 듯.
    build:
      context: .
      dockerfile: meet-api.Dockerfile
      
    environment:
      # express의 환경변수 설정을 분화시킴.
      - MEET_NODE_ENV=production
    # nginx에서 host의 3001번을 https로 하였음
    ports:
      - "80:3000"
    
    # 그냥 npm start해도 되긴하는데, log를 어떻게 남길 지는 고민해봐야겠다.
    # 우선은 docker attach CONTAINER_NAME으로 가능은 함.
    command:
      - npm
      - start
    # volumes:
    #   - ./:/app/